### ISSUE TITLE
Egrep string in FV2 status script 

### ISSUE THREAD

**Issue by elvisizer** [rtrouton/rtrouton_scripts#11]
Hi Rich- in the FV2 status reporting scripts, the egrep string that is supposed to limit the results returned from diskutil cs list isn't actually doing that for me- if I have external drives connected that were encrypted via the Finder, the script returns status for all, not just the first drive. . . . which makes the comparison logic later in the script fail.
I added the -m 1 switch to all the grep commands, which seems to fix it.  But I'm curious if there's a reason you didn't do that in the first place . . . . Is there a problem with using -m 1 to limit the results?

**Comment by rtrouton** [comment]
I finally went back and fixed the script, so it now is specifically looking at the boot drive's FileVault 2 status and ignores other mounted CoreStorage volumes.
