### ISSUE TITLE
disable_apple_icloud_and_diagnostic_pop_ups.sh: chown: basename "${USER_HOME}": illegal user name

### ISSUE THREAD

**Issue by morgrowe** [rtrouton/rtrouton_scripts#19]
I've been playing around with your "disable_apple_icloud_and_diagnostic_pop_ups.sh" script.  I got the following error whilst executing it (sudo bash ~/path/to/script.sh):

chown: basename "${USER_HOME}": illegal user name

I was able to rectify the issue by editing line 36:

USER_UID='basename "${USER_HOME}"'

to:

USER_UID=$(basename "${USER_HOME}")

I'm using OS X 10.10.1.

Not 100% sure why this fixed the issue and I haven't done any extensive testing, but after making the change the script executes without any problems.

Thanks!

**Comment by rtrouton** [comment]
I don't believe I've ever tried to execute this script from inside one of the home folders that the script is supposed to edit. I always assumed there would be a problem, and sure enough; there is one! Thanks for the heads-up on this.

**Comment by morgrowe** [comment]
No problem. :)
