### ISSUE TITLE
Issue with El Capitan

### ISSUE THREAD

**Issue by egraf620** [rtrouton/rtrouton_scripts#22]
This has not been working for me on El Capitan. Have other people been having an issue?

**Comment by JohnSlaughter** [comment]
"This" is a lot of scripts.   Specifically which are you having issues with, and what are the specifics of those issues?

**Comment by egraf620** [comment]
oh sorry it didn't specify. I am having problems with the disable_apple_icloud_and_diagnostic_pop_ups.sh script. It doesn't prevent the iCloud login from coming up.

**Comment by rtrouton** [comment]
@egraf620, how are you deploying the script? I generally have mine set to run at startup.

**Comment by apettinen** [comment]
Instead of the script, the disabling can be done with a profile. The upside is that the profile is persistent between upgrades (tested in 10.9 -> 10.10 -> 10.11).

There's a couple of new keys in El Cap:
DidSeeSyncSetup2
"LastSeeniCloudSecurityProductVersion.Dev1" = "10.11";

**Comment by rtrouton** [comment]
@apettinen's point about using a profile instead of a script is a good one. Nick McSpadden has one available here:

https://github.com/nmcspadden/Profiles/blob/master/SetupAssistant-10.11.mobileconfig

I have not observed that the **DidSeeSyncSetup2** or **LastSeeniCloudSecurityProductVersion.Dev1** keys are necessary for El Capitan. The **disable_apple_icloud_and_diagnostic_pop_ups** script as it exists is working OK for me when setting up new El Capitan machines. 

The iCloud screen that pops up between upgrades (like the one that pops up after upgrading from 10.11.0 to 10.11.1) is proving a bit harder to suppress.

**Comment by apettinen** [comment]
Yeah, Nick's profile is nice. But then there's this way to do it:
https://gist.github.com/apettinen/d0b6568116c4ae06ec4b

It has been persistent in my testing (10.9.5->10.10.5->10.11->10.11.1). No popups observed, as the key SkipCloudSetup can be set as a system level profile, as done in the example I put in the gist.

You can easily create that with Profile Manager, in Login Window -preferences. Just edit the other unnecessary stuff away (see the gist for advice).

**Comment by Lollaskates** [comment]
I am also experiencing the same behavior with disable_apple_icloud_and_diagnostic_pop_ups.sh

It has been working fine for a long long time, at least for 10.9 and 10.10. During the 10.10.5 workflow I have it works as expected, but when I used a 10.11.1 15B42 base the icloud window pops up during first login and is interfering with the imaging process.

I have the following keys being updated to the current build / version and also bool TRUE:

DidSeeCloudSetup -bool TRUE
DidSeeSyncSetup -bool TRUE
DidSeeSyncSetup2 -bool TRUE
GestureMovieSeen none
LastSeenCloudProductVersion "${sw_vers}"
LastSeenBuddyBuildVersion "${sw_build}"
LastPreLoginTasksPerformedBuild "${sw_build}"
LastPreLoginTasksPerformedVersion "${sw_vers}"
DidSeeiCloudSecuritySetup -bool TRUE
LastSeeniCloudSecurityProductVersion.Dev1 "${sw_vers}"

As you can see, I've tried it all, and it is not suppressing on 10.11.1 15B42

**Comment by bigjolly1** [comment]
I am using the Disable Apple iCloud and Diagnotic Pop-Ups.pkg with createOSXinstaller on 10.11.4. I am getting this error message from createOSXinstaller:
_path-to-createOSXinstallPkg-master_/Disable Apple iCloud and Diagnostic Pop-Ups.pkg is not a flat distribution package. This will cause a 10.10+ install to fail.

**Comment by rtrouton** [comment]
@bigjolly1,

Correct, the **Disable Apple iCloud and Diagnotic Pop-Ups.pkg** is not a distribution-style installer package. Instead, it is a flat component package. For more information on this issue, and a way to convert the existing **Disable Apple iCloud and Diagnotic Pop-Ups.pkg** into a distribution-style installer package, please see the link below for **createOSXinstallPkg**:

[https://github.com/munki/createOSXinstallPkg#further-note-on-additional-packages-and-yosemite](https://github.com/munki/createOSXinstallPkg#further-note-on-additional-packages-and-yosemite)

**Comment by hardlydavis** [comment]
Hi rtrouton  +anyone else who has had success with this!
First of all, thank you, very helpful indeed. 
Secondly: "I generally have mine set to run at startup." 
How would you recommend doing so?
I'm attempting to use a launchdaemon like your example in https://github.com/rtrouton/rtrouton_scripts/blob/master/rtrouton_scripts/rename_mac_hostname/com.company.rename_mac.plist
But I just wanted to check that this would run sufficeintly early to be effective?
Thanks again,
David
