### ISSUE TITLE
installer : must be run as root to install this package

### ISSUE THREAD

**Issue by m3ir3** [rtrouton/rtrouton_scripts#26]
Hi  ,

I having some problem when trying to run "install_latest_adobe_flash_player" in a shell script .
Been trying with 10.7 & 10.10 and get the same error "installer : must be run as root to install this package" without installing flash .
what am I missing in here?

TiA

**Comment by chasetb** [comment]
Are you running the script with `sudo`? The script needs admin privileges to install Flash.

**Comment by thealanberman** [comment]
If it absolutely must be run as root, it's probably worth adding a check to ensure that the script is running as root.

`[ "$EUID" -ne 0 ] && { echo "Please run as root"; exit; }`

**Comment by rtrouton** [comment]
This script will need to be run with root privileges in order to install Flash. The error message generated by the`installer` tool should be enough of a notification for folks who are running without root privileges.
