### ISSUE TITLE
filevault_2_encryption_check_extension_attribute.sh not compatible with APFS volumes

### ISSUE THREAD

**Issue by mpanighetti** [rtrouton/rtrouton_scripts#32]
I realize this is probably a known/obvious issue but thought it worth reporting for tracking purposes. Currently, when running `filevault_2_encryption_check_extension_attribute.sh` on a Mac with an APFS startup volume (i.e. macOS High Sierra Macs booting from SSDs), the script returns `<result>FileVault 2 Encryption Not Enabled</result>`. This is because the script only considers CoreStorage volumes when determining FileVault status, and because APFS ≠ CoreStorage, the check incorrectly assumes no disk encryption.

Right now the script starts by checking operating system build before proceeding with the CoreStorage check, but it might be more prudent to restructure it such that it first determines the File System Personality attribute (`diskutil info / | awk -F: '/File System Personality/ {print $NF}' | sed 's/^ *//` has been a reliable lookup method in my testing in macOS 10.12 and 10.13).

Recommended script workflow:

- If it's APFS, run checks specific to that disk type (could run `fdesetup status` for on/off and percentage encryption/decryption).
- If it's HFS+, check for CoreStorage and run the corresponding checks there; if it's not CoreStorage, report that FileVault is disabled.

**Comment by rtrouton** [comment]
Correct, the script only considers CoreStorage. I've written a separate script for APFS: 

https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/check_apfs_encryption
