### ISSUE TITLE
Script Link is Dead

### ISSUE THREAD

**Issue by hieronymous** [rtrouton/rtrouton_scripts#37]
Hello,

It appears that the link to the actual script to migrate the local to network account is inactive.  It also appears to appear that the homesite for the link, blog.macadmincorner.com is also dead.  

Anyone still have a copy of the script, that could post please?  Good luck fellow Mac admins!

**Comment by jhbush** [comment]
@hieronymous you may want to check out Pat's repo https://github.com/patgmac

**Comment by hieronymous** [comment]
That was fast! Thanks!
