### ISSUE TITLE
New Prompt is not Handled

### ISSUE THREAD

**Issue by sloth8871** [rtrouton/rtrouton_scripts#44]
There appears to be a new prompt for Enhanced Error reporting that is not suppressed by the script in at least version 16.15 (180709):
![hui_office_mac16](https://user-images.githubusercontent.com/41362186/42867953-e2606022-8a25-11e8-9345-2cb4569a2aa5.JPG)

Adding the following line in the DisableOffice2016FirstRun function seems to suppress 
/usr/bin/defaults write /Library/Preferences/com.microsoft."$app" kFRETelemetryConsentKey -bool true

Beyond that I do not know how to validate if that fully disables error reporting but it at least disabled the prompt upon first app run.

**Comment by rtrouton** [comment]
These days, I'd recommend using a profile over a script to suppress these prompts, but pull requests will be accepted.

**Comment by rtrouton** [comment]
No response, so I'm closing the issue.
