### ISSUE TITLE
JNLP not able to launch 

### ISSUE THREAD

**Issue by Rajsekhar355** [rtrouton/rtrouton_scripts#45]
I have tried two ways

1. If already installed Java manually then if we run script its working as expected. I'm able to launch JNLP on click of button in chrome.

2. If i directly installed script Java -version is fine but i'm not able to launch in chrome (MAC laptop).

**Comment by rtrouton** [comment]
Chrome no longer supports NPAPI browser plug-ins and the Java plug-in is a NPAPI plug-in. Firefox and Safari have also discontinued support for NPAPI.

For more details on Chrome and NPAPI, please see the link below: 

https://blog.chromium.org/2013/09/saying-goodbye-to-our-old-friend-npapi.html
