### ISSUE TITLE
Unable to identify download URL for requested Oracle Java 10 JDK Critical Patch Update (CPU).

### ISSUE THREAD

**Issue by dannyhanes** [rtrouton/rtrouton_scripts#47]
Script seems to fail on Mojave. 

Error message in install.log:
`Unable to identify download URL for requested Oracle Java 10 JDK Critical Patch Update (CPU).`

**Comment by rtrouton** [comment]
Java 10 JDK has been EOL'd by Oracle in favor of Java 11 JDK. I have removed this script from the repository and am closing this issue.
