### ISSUE TITLE
Jamf_Pro_Computer_Policy_Download.sh Includes Jamf Remote Policies

### ISSUE THREAD

**Issue by apizz** [rtrouton/rtrouton_scripts#54]
Was just testing the https://github.com/rtrouton/rtrouton_scripts/blob/master/rtrouton_scripts/Casper_Scripts/Jamf_Pro_Computer_Policy_Download/Jamf_Pro_Computer_Policy_Download.sh script and it appears that this will download **all** policies, including those created by Jamf Remote.

Is it possible to update the script such that it only includes those policies listed in the Computer Policies area?

Looking at the output XML, I can't tell any unique information other than the title containing a colon `:` but this results in `(colon)` in the actual output .xml filename.

The root problem here appears that despite these policies being triggered by Jamf Remote, the policy is listed as enabled: `<enabled>true</enabled>`

Not sure what the best solution is here to address this

**Comment by rtrouton** [comment]
My own shop isn't using Casper Remote, so I'm not able to do testing to see if there's a unique identifier for Casper Remote policies. If you find one, please let me know.

**Comment by apizz** [comment]
@rtrouton OK, will do some testing in the near future

**Comment by apizz** [comment]
I meant to address this, so sorry for leaving open so long. I made a few improvements in our environment which I'm not sure you'd accept in PR if it currently operates the way you need it to
