### ISSUE TITLE
XProtect: not a real issue though

### ISSUE THREAD

**Issue by SardinhaPT** [rtrouton/rtrouton_scripts#60]
First of all, thanks for this piece of work. Really helpful!
Please allow me a very quick question, and apologise if this is not really an issue (was the only I found to contact you).

It is known that it is possible to enable/disable and check status for **Gatekeeper** using the following command (for example): 
- spctl --status
- sudo spctl --master-disable 

My question is: is there a way to achieve the same for **XProtect**?
Many thanks in advance.

**Comment by rtrouton** [comment]
You want to enable and disable XProtect? I don't know how to do that.
