### ISSUE TITLE
Operation not Premitted

### ISSUE THREAD

**Issue by jscocca** [rtrouton/rtrouton_scripts#62]
When I run the script it tried to rename the home director to username.old at this point the script comes back and gives error operation not permitted.
The home directory is still there, but the account gets deleted.
I would like to be able to use this script as I have a client who has over 50 macs to domain.

Thank you.

**Comment by rtrouton** [comment]
I don't know which script you're referring to. More details, please.

**Comment by jscocca** [comment]
Oh my bad, I am using MigrateLocalUserToADDomainAcct.command.

**Comment by martinp0** [comment]
Hi, @jscocca 

I had similar issue, but solved it by disable rootless in Recovery mode with `csrutil disable`, than re-run chmod and it was fine.. than it is a good idea to enable csrutil again

https://www.quora.com/How-do-I-turn-off-the-rootless-in-OS-X-El-Capitan-10-11

**Comment by rtrouton** [comment]
If this issue is happening on Mojave, it's because of the user privacy protections which Apple has applied to the account home folders. Unfortunately, that's not an issue with how the script works so it can't be fixed within the script. 

Turning off SIP also disables the user privacy protections.
