### ISSUE TITLE
That no longer works with latest Mojave update

### ISSUE THREAD

**Issue by scerazy** [rtrouton/rtrouton_scripts#65]
This:
disable_apple_icloud_data_privacy_diagnostic_touch_id_siri_activation_lock_and_screentime_pop_ups
seems to no longer work with latest Mojave update, only profile route seems to work now:
https://github.com/rtrouton/profiles/tree/master/SkipiCloudSetup

**Comment by csteelatgburg** [comment]
I also tried the SkipTouchITSetup profile and I'm still getting prompted to set it up. At this point I have disabled everything that I can find related to TouchID and it is still popping up on login for new user accounts.
