### ISSUE TITLE
Incorrectly reports as unencrypted drive

### ISSUE THREAD

**Issue by shhtephe** [rtrouton/rtrouton_scripts#67]
Currently running 10.15.6. Script attempts to check for corestorage volume and fails. As such it reports "FileVault 2 Encryption Not Enabled"
![image](https://user-images.githubusercontent.com/10876562/87816426-4a160380-c835-11ea-967c-207c79cf67f2.png)

However, FileVault 2 is enabled and shows encrypted in both the system and in Jamf.
![image](https://user-images.githubusercontent.com/10876562/87816473-5f8b2d80-c835-11ea-9e84-bbcfd91acc86.png)

![image](https://user-images.githubusercontent.com/10876562/87816628-a547f600-c835-11ea-9557-b84916aa62db.png)

This doesn't seem to be expected behavior. Glad to help with any testing you need to figure this out.

**Comment by rtrouton** [comment]
The script is working correctly, as FileVault encryption uses CoreStorage volumes on drives formatted with the HFS+ file system. The last OS which supported booting from HFS+ is macOS High Sierra 10.13.x. 

Apple File System (APFS), which succeeded HFS+ as Apple’s default file system, has built-in native encryption capabilities and does not use Core Storage volumes for FileVault encryption.

I recommend transitioning to using this extension attribute instead: [https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/Casper_Extension_Attributes/check_apfs_encryption](https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/Casper_Extension_Attributes/check_apfs_encryption)
