### ISSUE TITLE
detect_installed_32_bit_apps.sh not working on 10.15.7

### ISSUE THREAD

**Issue by micmil** [rtrouton/rtrouton_scripts#82]
I am having trouble with the script detect_installed_32_bit_apps.sh running on macOS 10.15.7. It does not appear to be detecting any 32-bit applications in the Applications folder. Have two 32-bit apps in the folder currently. I verified they are detected by System Profiler by pulling up the list manually. Both apps are listed correctly as 32-bit. Running the script does not produce any results.

**Comment by aduffner** [comment]
Does it produce an empty file at "/private/var/log/32bit_apps_installed.log"?

**Comment by micmil** [comment]
No it says "No 32-bit applications found in /Applications, /Library or /usr/local."

**Comment by aduffner** [comment]
Okay, I looked into it. The script does a simple grep for "64-bit (Intel): No" and forwards the result of the command "/usr/sbin/system_profiler SPApplicationsDataType". You could look at the result of the command to figure out how to find a more reliable way.

**Comment by micmil** [comment]
I think I got it working. Looks like Apple changed the output of the "system_profiler SPApplicationsDataType". This line needs to be changed to:

`# get all non-64 Bit applications from the initial list
		ThirtyTwoBit_app_list=$(echo "$ThirtyTwoBit_app_list" | /usr/bin/grep -B1 "Kind: 32-bit (Unsupported)")`

The previous grep was pulling lines after the application type; it now needs to pull only one line above. They also changed how the 32/64 type is output. I don't have an example of the old output, but here's an example of the new output on Catalina:

```
AppleMobileDeviceHelper:

      Version: 5.0
      Obtained from: Apple
      Last Modified: 2/26/20, 1:51 AM
      Signed by: Software Signing, Apple Code Signing Certification Authority, Apple Root CA
      Location: /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/AppleMobileDeviceHelper.app
      Kind: 64-bit
```

I have to get my Big Sur test box running first before I test it there (ugh).
