### ISSUE TITLE
install_rosetta_on_apple_silicon problem with Monterey

### ISSUE THREAD

**Issue by emendelson** [rtrouton/rtrouton_scripts#86]
I was looking for a way that an AppleScript could detect if Rosetta 2 is installed, and found this very impressive script. I found two problems with the Monterey beta. First, when I ran the script on an M1 system where Rosetta 2 was already installed (but I hadn't restarted the system), the script reinstalled Rosetta 2. 

Next, when I ran the script again in the same session, it gave this error:

`2021-07-04 23:05:36.579 softwareupdate[4759:66089] Package Authoring Error: 071-59957: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute`

I don't pretend to understand this at all. Meanwhile, thank you for writing this script, and I hope it's easy to update it for Monterey.

**Comment by rtrouton** [comment]
That's an issue with Apple's `softwareupdate` tool and isn't from my script.
