### ISSUE TITLE
Stupid question: is installing the 'Resize VM Boot Partition.pkg' supposed to just run the resize script on Big Sur 11.7.3?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [rtrouton/rtrouton_scripts#98]
The only thing that seems to happen is to add a receipt. The boot volume didn't get resized.

**Comment by rtrouton** [comment]
Correct, it runs the following script:

https://github.com/rtrouton/rtrouton_scripts/blob/main/rtrouton_scripts/resize_vm_boot_partition/resize_vm_boot_partition.sh

Do you have any logs? Since you were running it via an installer package, the output for the resizing should have gone to `/var/log/install.log`.

**Comment by UNIVAC-Colonel-Panic** [comment]
Thanks for your prompt reply. I didn't know about _/var/log/install.log_ before. Here's what it shows, with date/timestamp removed for brevity:

```
./postinstall: Started APFS operation
./postinstall: Error: -69743: The new size must be different than the existing size
```

I get the same error after separately downloading and running _resize_vm_boot_partition.sh_. I guess the macOS installer doesn't check the return code from the postinstall script as it declared _Resize VM Boot Partition.pkg_ installed successfully.

I know the error has nothing to do with _Resize VM Boot Partition.pkg_ and I don't have a solution but in case anyone else runs into this, here's the diskutil info. I was trying to expand the startup disk to the full 107.4gb. I can use _resize_vm_boot_partition.sh_ manually to shrink it, then expand it, but can't expand it beyond the 53.5gb already defined.

~~~
/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *107.4 GB   disk1
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk1s1
   2:                 Apple_APFS ⁨Container disk2⁩         53.5 GB    disk1s2

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +53.5 GB    disk2
                                 Physical Store disk1s2
   1:                APFS Volume ⁨Big-Sur-II - Data⁩       19.2 GB    disk2s1
   2:                APFS Volume ⁨Preboot⁩                 310.3 MB   disk2s2
   3:                APFS Volume ⁨Recovery⁩                620.3 MB   disk2s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk2s4
   5:                APFS Volume ⁨Big-Sur-II⁩              15.3 GB    disk2s5
~~~
