### ISSUE TITLE
Please update to work with apple silicon 

### ISSUE THREAD

**Issue by Appsins** [rtrouton/rtrouton_scripts#99]
It's doesn't work with apple silicon please update :)

**Comment by rtrouton** [comment]
Apple made significant changes to how booting to recovery mode works on Apple Silicon Macs. To the best of my knowledge, this is the sole way to boot into Recovery on Macs with Apple Silicon processors (like M1 and M2 Macs):

* Power off Mac
* Press and hold the power button until the system volume and the Options button appear.

**Comment by Appsins** [comment]
There is no way to boot to diagnostics mode with command or sh file?

**Comment by rtrouton** [comment]
Not for Apple Silicon Macs to the best of my knowledge. If you find a way, please let me know.
